import type { ReviewField } from '../models/extraction'

type ReviewSummaryProps = { fields: ReviewField[]; missingCount: number; activeFilter: 'all' | 'missing' | 'low-confidence' | 'complete'; onFilterChange: (filter: 'all' | 'missing' | 'low-confidence' | 'complete') => void }

export function ReviewSummary({ fields, missingCount, activeFilter, onFilterChange }: ReviewSummaryProps) {
  const lowConfidenceCount = fields.filter((field) => field.confidence !== undefined && field.confidence !== null && field.confidence < 0.7).length
  const summaryItemClassName = 'w-full rounded-lg border px-[12px] py-[10px] text-left transition-colors dark:bg-[#090f15]'

  return <div className="my-5 grid grid-cols-3 gap-2.5 max-[820px]:grid-cols-1"><button type="button" className={`${summaryItemClassName} ${activeFilter === 'all' ? 'border-[#1677b7] bg-[#edf7ff] dark:border-[#5f8fb1] dark:bg-[#0d1820]' : 'border-[#e1e7e5] bg-white/90 hover:border-[#86b9d9] dark:border-[#243846] dark:bg-[#060d13] dark:hover:border-[#5f9bc4]'} dark:border-[#444]`} aria-pressed={activeFilter === 'all'} onClick={() => onFilterChange('all')}><span className="block text-[9px] font-semibold uppercase tracking-[0.08em] text-[#6c7a79] dark:text-[#b8c5c4]">欄位總數</span><strong className="mt-[4px] block text-[20px] leading-none text-[#1f2a29] dark:text-[#edf5f3]">{fields.length}</strong></button><button type="button" className={`${summaryItemClassName} ${activeFilter === 'missing' ? 'border-[#e4572e] bg-[#fff2eb] dark:border-[#ff9b6b] dark:bg-[#1d1715]' : 'border-[#e1e7e5] bg-white/90 hover:border-[#e8a17d] dark:border-[#243846] dark:bg-[#060d13] dark:hover:border-[#ff9b6b]'} dark:border-[#444]`} aria-pressed={activeFilter === 'missing'} onClick={() => onFilterChange('missing')}><span className="block text-[9px] font-semibold uppercase tracking-[0.08em] text-[#6c7a79] dark:text-[#b8c5c4]">待補必填</span><strong className={`mt-[4px] block text-[20px] leading-none ${missingCount ? 'text-[#e4572e] dark:text-[#ffb08e]' : 'text-[#1f2a29] dark:text-[#edf5f3]'}`}>{missingCount}</strong></button><button type="button" className={`${summaryItemClassName} ${activeFilter === 'low-confidence' ? 'border-[#d9a33d] bg-[#fff8e8] dark:border-[#ffc256] dark:bg-[#1a1914]' : 'border-[#e1e7e5] bg-white/90 hover:border-[#d9b05b] dark:border-[#243846] dark:bg-[#060d13] dark:hover:border-[#ffc256]'} dark:border-[#444]`} aria-pressed={activeFilter === 'low-confidence'} onClick={() => onFilterChange('low-confidence')}><span className="block text-[9px] font-semibold uppercase tracking-[0.08em] text-[#6c7a79] dark:text-[#b8c5c4]">建議檢查</span><strong className="mt-[4px] block text-[20px] leading-none text-[#1f2a29] dark:text-[#edf5f3]">{lowConfidenceCount}</strong></button></div>
}
