import { CircleAlert, PencilLine } from 'lucide-react'
import { Input } from './ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select'
import type { ReviewField as ReviewFieldModel } from '../models/extraction'

type ReviewFieldProps = { field: ReviewFieldModel; onChange: (id: string, value: string) => void }

export function ReviewField({ field, onChange }: ReviewFieldProps) {
  const isMissing = field.required && !field.value.trim()
  const isLowConfidence = field.confidence !== undefined && field.confidence !== null && field.confidence < 0.7
  const isCustomValue = Boolean(field.candidates && !field.candidates.includes(field.value))
  return <label className={`grid grid-cols-[minmax(150px,190px)_minmax(0,1fr)] items-start gap-3 border-b border-[#edf1ef] py-1.5 last:border-b-0 dark:border-[#2e3736] max-[820px]:grid-cols-1 max-[820px]:gap-1.5 ${isMissing ? 'pb-4' : ''}`}><span className="min-w-0 pt-[6px] text-[12px] leading-[1.35] text-[#3a4342] dark:text-[#e8efee]"><span className="flex items-center gap-1.5"><span className="break-words">{field.label}</span>{field.required && <em className="inline-flex items-center rounded-full bg-[#edf3f1] px-[5px] py-[1px] text-[8px] font-semibold not-italic text-[#4a5857] dark:bg-[#2a3433] dark:text-[#dfe9e7]">必填</em>}</span><small className="mt-[2px] flex flex-wrap items-center gap-1 text-[9px] text-[#77827f] dark:text-[#9ab0ac]">第 {field.page} 頁{isLowConfidence && <b className="inline-flex items-center gap-1 rounded-full bg-[#fff1e9] px-[5px] py-[1px] font-semibold text-[#e4572e] dark:bg-[#3c2b22] dark:text-[#ffb08e]"><CircleAlert size={10} />建議</b>}</small></span><span className="relative flex min-w-0 items-center"><span className="relative w-full">{field.candidates ? <>{<Select value={isCustomValue ? '__custom__' : field.value} onValueChange={(value) => onChange(field.id, value === '__custom__' ? '' : value)}><SelectTrigger className="h-8 border-[#e1e8e6] bg-white px-2.5 text-[12px] text-[#2a2f2e] shadow-none dark:border-[#3d4948] dark:bg-[#141b1b] dark:text-[#edf5f3]" aria-invalid={isMissing}><SelectValue /></SelectTrigger><SelectContent>{field.candidates.map((candidate) => <SelectItem key={candidate} value={candidate}>{candidate}</SelectItem>)}<SelectItem value="__custom__">自訂輸入</SelectItem></SelectContent></Select>}{isCustomValue && <Input className="mt-1.5 h-8 border-[#e1e8e6] bg-white px-2.5 text-[12px] text-[#2a2f2e] dark:border-[#3d4948] dark:bg-[#141b1b] dark:text-[#edf5f3]" aria-invalid={isMissing} value={field.value} placeholder="請輸入自訂值" onChange={(event) => onChange(field.id, event.target.value)} />}</> : <Input className="h-8 border-[#e1e8e6] bg-white px-2.5 text-[12px] text-[#2a2f2e] dark:border-[#3d4948] dark:bg-[#141b1b] dark:text-[#edf5f3]" aria-invalid={isMissing} value={field.value} placeholder="請輸入" onChange={(event) => onChange(field.id, event.target.value)} />}{isMissing && <small className="mt-1.5 block text-[9px] font-semibold text-[#e4572e] dark:text-[#ffb08e]">必填</small>}</span><PencilLine className="pointer-events-none absolute right-[9px] top-1/2 -translate-y-1/2 text-[#a7b8b5]" size={12} /></span></label>
}
