import { ArrowLeft, ArrowRight, Check, FileText } from 'lucide-react'
import { Button } from './ui/button'
import { Alert } from './ui/alert'
import { ReviewGroup } from './ReviewGroup'
import { ReviewSummary } from './ReviewSummary'
import type { ReviewField } from '../models/extraction'

type ReviewWorkspaceProps = { filename?: string; fields: ReviewField[]; groups: readonly string[]; expandedGroups: string[]; missingFields: ReviewField[]; onToggleGroup: (group: string) => void; onFieldChange: (id: string, value: string) => void; onRestart: () => void; onComplete: () => void }

export function ReviewWorkspace({ filename, fields, groups, expandedGroups, missingFields, onToggleGroup, onFieldChange, onRestart, onComplete }: ReviewWorkspaceProps) {
  return <div className="mx-auto max-w-[880px]"><div className="mb-[42px] flex items-start justify-between"><div><span className="text-[10px] font-extrabold tracking-[1.5px] text-[#888] dark:text-[#999]">STEP 03 / REVIEW</span><h2 className="mt-3 text-[clamp(26px,3vw,36px)] leading-[1.2] text-[#202827] dark:text-white">確認解析結果</h2></div><span className="border border-[#b9cbc5] bg-[#e8efec] px-2.5 py-[7px] text-[10px] font-extrabold tracking-[1px] text-[#51625e] dark:border-[#666] dark:bg-[#222] dark:text-[#ddd]">MOCK DATA</span></div><div className="mt-[-16px] flex items-center justify-between gap-[13px] border border-[#d6e0dc] bg-white px-[18px] py-4 dark:border-[#444] dark:bg-[#222]"><div className="flex items-center gap-2.5 text-[#2c837a] dark:text-[#ddd]"><FileText size={19} /><strong className="text-[13px] text-[#222] dark:text-[#eee]">{filename || '食品標示文件.pdf'}</strong><span className="bg-[#e5f1ee] px-2 py-1 text-[10px] text-[#216b64] dark:bg-[#333] dark:text-[#ddd]">解析完成</span></div><Button type="button" variant="secondary" size="compact" onClick={onRestart}><ArrowLeft size={15} />重新上傳</Button></div><ReviewSummary fields={fields} missingCount={missingFields.length} /><div>{groups.map((group) => <ReviewGroup key={group} name={group} fields={fields.filter((field) => field.group === group)} expanded={expandedGroups.includes(group)} onToggle={() => onToggleGroup(group)} onFieldChange={onFieldChange} />)}</div><div className="sticky bottom-0 mt-[30px] flex items-center justify-end gap-[13px] bg-[linear-gradient(transparent,#f1f5f3_22%)] py-4 pb-[3px] dark:bg-[linear-gradient(transparent,#111_22%)] max-[820px]:flex-col max-[820px]:items-start"><Alert tone={missingFields.length ? 'warning' : 'success'}>{missingFields.length ? <>還有 {missingFields.length} 個必填欄位待補</> : <><Check size={16} />所有必填欄位已完成</>}</Alert><Button type="button" className="max-[820px]:w-full" disabled={missingFields.length > 0} onClick={onComplete}>確認送出<ArrowRight size={17} /></Button></div></div>
}
